import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/globals.scss";
import FontProvider from "../components/elements/FontProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontProvider />
      </head>
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
