"use client";

import TableBuilder from "@/components/TableBuilder";
import invoices from "@/data/invoices.json";
import clients from "@/data/clients.json";
import projects from "@/data/projects.json";
import users from "@/data/users.json";
import Image from "next/image";
import { Column } from "@/types/table";
import { ReactNode } from "react";

const clientOptions = clients.map((c) => ({ id: c.id, name: c.client_name }));
const projectOptions = projects.projects.map((p) => ({ id: p.id, name: p.name }));
const statusOptions = [
  { id: "unpaid", name: "Unpaid" },
  { id: "paid", name: "Paid" },
  { id: "partial", name: "Partial" },
];
const userOptions = users.users.map((u) => ({ id: u.id, name: u.name })).concat([{ id: "auto", name: "Auto" }]);

type InvoiceRow = typeof invoices[number] & { id: string };
const invoicesData: InvoiceRow[] = invoices.map((inv) => ({ ...inv, id: inv.invoice_id }));

const columns: Column<InvoiceRow>[] = [
  {
    key: "invoice_id",
    label: "Invoice ID",
    sortable: true,
  },
  {
    key: "client_id",
    label: "Client",
    filterable: true,
    options: clientOptions,
    render: (value: unknown, row: InvoiceRow): ReactNode => {
      const client = clients.find((c) => c.id === row.client_id);
      return (
        <span className="flex items-center gap-2">
          {client?.client_name}
          {client?.avatar && (
            <Image src={client.avatar} alt={client.client_name} width={24} height={24} className="rounded-full" />
          )}
        </span>
      );
    },
  },
  {
    key: "project_id",
    label: "Project",
    filterable: true,
    options: projectOptions,
    render: (value: unknown, row: InvoiceRow): ReactNode => {
      const project = projects.projects.find((p) => p.id === row.project_id);
      return project?.name || row.project_id;
    },
  },
  {
    key: "items",
    label: "Items",
    render: (value: unknown, row: InvoiceRow): ReactNode => row.items.length,
  },
  {
    key: "total",
    label: "Total",
    sortable: true,
    render: (value: unknown) => `$${Number(value).toLocaleString()}`,
  },
  {
    key: "status",
    label: "Status",
    filterable: true,
    options: statusOptions,
    render: (value: unknown): ReactNode => {
      const status = statusOptions.find((s) => s.id === value);
      return status ? status.name : String(value);
    },
  },
  {
    key: "issue_date",
    label: "Issue Date",
    sortable: true,
    render: (value: unknown) => new Date(String(value)).toLocaleDateString(),
  },
  {
    key: "due_date",
    label: "Due Date",
    sortable: true,
    render: (value: unknown) => new Date(String(value)).toLocaleDateString(),
  },
  {
    key: "generated_by",
    label: "Generated By",
    filterable: true,
    options: userOptions,
    render: (value: unknown): ReactNode => {
      const user = userOptions.find((u) => u.id === value);
      return user ? user.name : String(value);
    },
  },
];

export default function InvoicesPage() {
  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">Invoices</h1>
        <p className="mt-1 text-sm text-gray-500">
          List of all invoices for clients and projects
        </p>
      </div>
      <TableBuilder data={invoicesData} columns={columns} />
    </div>
  );
} 